version: '2'
services:
    challengemyteam-app:
        image: challengemyteam
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://challengemyteam-mysql:3306/challengemyteam?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=challengemyteam-elasticsearch:9300
        ports:
            - 8080:8080
    challengemyteam-mysql:
        extends:
            file: mysql.yml
            service: challengemyteam-mysql
    challengemyteam-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: challengemyteam-elasticsearch
